//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_SysUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AC_SysUsers()
        {
            this.AUTH_User_Menu = new HashSet<AUTH_User_Menu>();
            this.AUTH_User_Command = new HashSet<AUTH_User_Command>();
            this.AC_SysRoles = new HashSet<AC_SysRoles>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> IdSysSkin { get; set; }
        public Nullable<decimal> EnAccountType { get; set; }
        public string UserName { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<byte> PasswordType { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public bool LockoutEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public short AccessFailedCount { get; set; }
    
        public virtual BA_SysEnType BA_SysEnType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH_User_Menu> AUTH_User_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH_User_Command> AUTH_User_Command { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_SysRoles> AC_SysRoles { get; set; }
    }
}
