//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_SysCommand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_SysCommand()
        {
            this.AUTH_User_Command = new HashSet<AUTH_User_Command>();
            this.AC_SysRoles = new HashSet<AC_SysRoles>();
        }
    
        public string Code { get; set; }
        public Nullable<decimal> IdSysMenu { get; set; }
        public string CodeSysCommandType { get; set; }
        public string Name { get; set; }
        public string JsCode { get; set; }
        public bool IsGlobal { get; set; }
        public bool IsAuthority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH_User_Command> AUTH_User_Command { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_SysRoles> AC_SysRoles { get; set; }
    }
}
