//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_SysEnType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_SysEnType()
        {
            this.BA_SysEnType1 = new HashSet<BA_SysEnType>();
            this.BA_SysEnType11 = new HashSet<BA_SysEnType>();
            this.KS_Confirm = new HashSet<KS_Confirm>();
            this.KS_Customer = new HashSet<KS_Customer>();
            this.KS_Customer1 = new HashSet<KS_Customer>();
            this.KS_Customer2 = new HashSet<KS_Customer>();
            this.KS_Customer3 = new HashSet<KS_Customer>();
            this.KS_Customer4 = new HashSet<KS_Customer>();
            this.OR_Person = new HashSet<OR_Person>();
            this.OR_Person1 = new HashSet<OR_Person>();
            this.AC_SysUsers = new HashSet<AC_SysUsers>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> IdSysEnType { get; set; }
        public Nullable<decimal> IdParent { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSys { get; set; }
        public Nullable<bool> IsEnd { get; set; }
        public Nullable<byte> Level { get; set; }
        public string RefSource { get; set; }
        public string Memo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SysEnType> BA_SysEnType1 { get; set; }
        public virtual BA_SysEnType BA_SysEnType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SysEnType> BA_SysEnType11 { get; set; }
        public virtual BA_SysEnType BA_SysEnType3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Confirm> KS_Confirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Person> OR_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Person> OR_Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_SysUsers> AC_SysUsers { get; set; }
    }
}
