//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_SysMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_SysMenu()
        {
            this.BA_SysMenu1 = new HashSet<BA_SysMenu>();
            this.AC_SysRoles = new HashSet<AC_SysRoles>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> IdSysMenu { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public Nullable<byte> IconType { get; set; }
        public string IconColor { get; set; }
        public byte MenuType { get; set; }
        public string Url { get; set; }
        public Nullable<short> Order { get; set; }
        public Nullable<bool> IsSysDefine { get; set; }
        public string Params { get; set; }
        public bool IsAuthority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SysMenu> BA_SysMenu1 { get; set; }
        public virtual BA_SysMenu BA_SysMenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_SysRoles> AC_SysRoles { get; set; }
    }
}
