//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_Department()
        {
            this.OR_Department1 = new HashSet<OR_Department>();
            this.OR_Person = new HashSet<OR_Person>();
            this.REF_Person_Department = new HashSet<REF_Person_Department>();
        }
    
        public string Code { get; set; }
        public string CodeDepartment { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> iGrade { get; set; }
        public Nullable<bool> bEnd { get; set; }
        public string Person { get; set; }
        public string Memo { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Department> OR_Department1 { get; set; }
        public virtual OR_Department OR_Department2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Person> OR_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REF_Person_Department> REF_Person_Department { get; set; }
    }
}
