//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_Person()
        {
            this.OR_Person1 = new HashSet<OR_Person>();
            this.REF_Person_Department = new HashSet<REF_Person_Department>();
            this.KS_Customer_Approval = new HashSet<KS_Customer_Approval>();
            this.KS_Customer_Replenish = new HashSet<KS_Customer_Replenish>();
            this.KS_Confirm = new HashSet<KS_Confirm>();
            this.KS_Customer = new HashSet<KS_Customer>();
            this.KS_Customer1 = new HashSet<KS_Customer>();
            this.CS_CustomerService = new HashSet<CS_CustomerService>();
            this.ST_Store = new HashSet<ST_Store>();
            this.REF_STORE = new HashSet<ST_Store>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> IdSysArea { get; set; }
        public Nullable<decimal> IdDirectSuperior { get; set; }
        public string PsnNum { get; set; }
        public string Name { get; set; }
        public string NamePinYin { get; set; }
        public string NameCharFirst { get; set; }
        public string CodeDepartment { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string LeaveReson { get; set; }
        public Nullable<decimal> EnJob { get; set; }
        public Nullable<decimal> EnPersonType { get; set; }
        public string JobTitle { get; set; }
        public string JobNumber { get; set; }
        public byte Sex { get; set; }
        public string Skills { get; set; }
        public string IdentityDesc { get; set; }
        public string PsnMobilePhone { get; set; }
        public string PsnEmail { get; set; }
        public string PsnQQCode { get; set; }
        public string HeadUrl { get; set; }
        public Nullable<bool> IsHaveAccount { get; set; }
        public string LoginName { get; set; }
        public string OrgEmail { get; set; }
        public string WorkPlace { get; set; }
        public string Memo { get; set; }
        public string WeChatOpenId { get; set; }
        public Nullable<bool> ExternalBit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Person> OR_Person1 { get; set; }
        public virtual OR_Person OR_Person2 { get; set; }
        public virtual OR_Department OR_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REF_Person_Department> REF_Person_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer_Approval> KS_Customer_Approval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer_Replenish> KS_Customer_Replenish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Confirm> KS_Confirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_Customer> KS_Customer1 { get; set; }
        public virtual BA_SysEnType BA_SysEnType { get; set; }
        public virtual BA_SysEnType BA_SysEnType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_CustomerService> CS_CustomerService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Store> ST_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Store> REF_STORE { get; set; }
    }
}
