//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_Store()
        {
            this.REF_PERSON = new HashSet<OR_Person>();
        }
    
        public decimal Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> IdArea { get; set; }
        public string Address { get; set; }
        public string JoinPerson { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> IdSupervisor { get; set; }
        public Nullable<decimal> RegionId { get; set; }
        public Nullable<decimal> IdPersonRegion { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> IdPerson { get; set; }
    
        public virtual OR_Person OR_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_Person> REF_PERSON { get; set; }
    }
}
