//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Customer
    {
        public decimal Id { get; set; }
        public decimal IdPerson { get; set; }
        public Nullable<decimal> StateId { get; set; }
        public Nullable<byte> State { get; set; }
        public string SubclassName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
