//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Jusoft_PcStStore
    {
        public decimal Id { get; set; }
        public string Code { get; set; }
        public decimal IdSysUsers { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string JoinPerson { get; set; }
        public string Phone { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> IdArea { get; set; }
        public Nullable<decimal> IdPersonRegion { get; set; }
        public Nullable<decimal> IdSupervisor { get; set; }
        public Nullable<decimal> RegionId { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string RegionName { get; set; }
        public string PersonRegionName { get; set; }
        public string SupervisorName { get; set; }
    }
}
