//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Jusoft_PcSysEnType
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> IdParent { get; set; }
        public Nullable<decimal> IdSysEnType { get; set; }
        public string ParentName { get; set; }
        public string SysEnTypeName { get; set; }
    }
}
