//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jusoft.YiFang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Ks_DataList
    {
        public decimal IdPerson { get; set; }
        public decimal IdStore { get; set; }
        public string Code { get; set; }
        public string HeadPto { get; set; }
        public string StoreName { get; set; }
        public string Name { get; set; }
        public string PsnMobilePhone { get; set; }
        public decimal KS_ID { get; set; }
        public Nullable<decimal> StateId { get; set; }
        public Nullable<byte> State { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public decimal IdPersonSupervision { get; set; }
        public string SuperName { get; set; }
        public string HeadUrl { get; set; }
        public string EnTypeName { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
